<?php

$allAttributes = $block->getAdditionalData();
$attributes = ['dimensions', 'material', 'color'];
$finalAttributes = [];

// TODO this needs to be in viewmodel?
foreach($attributes as $attribute)  {
    if (array_key_exists($attribute,$allAttributes))
    {
        $finalAttributes[$attribute] = $allAttributes[$attribute];
        unset($allAttributes[$attribute]);
        $attributes = array_diff($attributes, array($attribute));
    }
};


if (count($allAttributes) >= count($attributes) && count($allAttributes) > 0) {

    for ($i = 0; $i < count($attributes); $i++) {

        $tempAttribute = current($allAttributes);
        $finalAttributes[$tempAttribute['label']] = $tempAttribute;
        unset($allAttributes[$tempAttribute['label']]);
    }
}

?>

<ul>
    <?php foreach ($finalAttributes as $attribute) : ?>

            <li><strong><?=$attribute['label'];?>: </strong><?=$attribute['value'];?></li>
    <?php endforeach; ?>
</ul>