<?php

$allAttributes = $block->getAdditionalData();

//echo '<pre>';
//echo var_dump($allAttributes);
//exit;

$attributes = ['dimensions', 'color', 'material']; // cant find dimensions?

foreach ($attributes as $attribute) {

    if(!empty($allAttributes[$attribute])) {
        echo ($allAttributes[$attribute]['label']).'-'.($allAttributes[$attribute]['value']) . '<br>';
    }

    //add dimensions attribute.

}


?>

<ul>
    <li>Test item 1</li>
    <li>Test item 2</li>
    <li>Test item 3</li>
</ul>


<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.</p>