<?php

$allAttributes = $block->getAdditionalData();
$attributes = ['dimensions', 'color', 'material'];

//echo '<pre>';
//echo var_dump($_product);
//exit;


?>

<ul>
    <?php foreach ($attributes as $attribute) : ?>
    <li><strong><?=$allAttributes[$attribute]['label'];?>: </strong><?=$allAttributes[$attribute]['value'];?></li>
    <?php endforeach; ?>
    <li style="color:red;">TODO if not exist</li>
</ul>


<p style="color:red;">TODO With the Fusion Backpack strapped on, every trek is an adventure - even a bus ride to work.</p>