<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

echo var_dump(json_encode($block->getQuantityValidators()));

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php
/** @var TYPE_NAME $attributeData */
$attributeData = $block->getData('viewModel');

/** @var TYPE_NAME $qty */
$qty = $attributeData->getQty($_product);
?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">

                        <!-- ko template: getTemplate() --><!-- /ko -->
                        <script type="text/x-magento-init">
                            {
                                "#custom-qty": {
                                    "Magento_Ui/js/core/app": {
                                        "components": {
                                            "qty-counter": {
                                                "component": "qty-counter",
                                                "config": {
                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                }
                                            }
                                         }
                                    }
                                }
                            }
                        </script>

                        <?php if ($block->displayProductStockStatus()) :?>
                            <div class="stock-status-group">
                                <?php if ($_product->isAvailable()) :?>
                                    <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                        <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                    </div>
                                    <div class="stock remaining"> <?= $qty;?> items available</div>
                                <?php else :?>
                                <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>